server:
  port: 3000

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  database: 'truthy'

jwt:
  expiresIn: 3600

app:
  name: 'Truthy'
  version: 'v0.1'
  description: 'Official Truthy API'
